-- Supabase SQL for `memes` table with `category` and `tags`
-- Run this file in the Supabase SQL editor (or include in migrations)

-- 1. DROP TABLE (Hapus tabel jika sudah ada, berhati-hatilah saat menggunakan ini!)
-- DROP TABLE IF EXISTS public.memes;

-- 2. CREATE TABLE (Membuat tabel memes)
CREATE TABLE IF NOT EXISTS public.memes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT NOT NULL,
    category TEXT,
    tags TEXT[]
);

-- 3. Mengaktifkan Row Level Security (RLS)
-- Di lingkungan produksi, Anda harus mendefinisikan kebijakan RLS yang ketat.
ALTER TABLE public.memes ENABLE ROW LEVEL SECURITY;

-- 4. Kebijakan RLS Dasar (Mengizinkan semua orang membaca data publik)
-- CATATAN: Supabase SDK Anda mengandalkan kebijakan ini.
CREATE POLICY "Enable read access for all users"
ON public.memes FOR SELECT
USING (TRUE);

-- 5. Kebijakan Dasar (Mengizinkan pengguna anonim untuk INSERT)
-- CATATAN: Kebijakan ini mengizinkan upload dari front-end Anda (tanpa login).
CREATE POLICY "Enable insert for authenticated users or anonymous"
ON public.memes FOR INSERT
WITH CHECK (TRUE);

-- 6. Kebijakan UPDATE / DELETE (opsional — tambahkan jika RLS diaktifkan)
-- Berikut contoh sangat permisif yang mengizinkan update/delete dari front-end.
-- Di produksi, ganti kondisi dengan pemeriksaan `auth.uid()` atau kolom owner.
CREATE POLICY "Enable update for all rows"
ON public.memes FOR UPDATE
USING (TRUE)
WITH CHECK (TRUE);

CREATE POLICY "Enable delete for all rows"
ON public.memes FOR DELETE
USING (TRUE);

-- NOTE: The above UPDATE/DELETE policies are permissive for quick testing/local use.
-- For a secure setup, scope policies to authenticated users and/or row owners.

-- ----------------------------------------------------------------------
-- 7. EXAMPLE: INSERT (Memasukkan Data Baru) with category + tags
-- ----------------------------------------------------------------------
INSERT INTO public.memes (title, description, image_url, category, tags)
VALUES (
    'Meme Pertama Saya',
    'Ini adalah contoh meme yang diunggah secara manual dengan kategori dan tag.',
    'https://via.placeholder.com/300/0000FF/FFFFFF?text=MANUAL_UPLOAD',
    'Funny',
    ARRAY['cats','wholesome']
);

-- ----------------------------------------------------------------------
-- 8. READ (Mengambil/Melihat Data)
-- ----------------------------------------------------------------------

-- Mengambil semua meme dan mengurutkannya dari yang terbaru
SELECT
    id,
    created_at,
    title,
    description,
    category,
    tags,
    image_url
FROM
    public.memes
ORDER BY
    created_at DESC;

-- Mengambil meme spesifik berdasarkan ID
SELECT
    *
FROM
    public.memes
WHERE
    id = 1; -- Ganti 1 dengan ID meme yang ingin Anda lihat

-- Mencari meme berdasarkan kata kunci (untuk fungsi pencarian pada title/description)
SELECT
    *
FROM
    public.memes
WHERE
    title ILIKE '%kucing%' OR description ILIKE '%kucing%';

-- Mencari meme yang memiliki tag tertentu (cont: tag 'cats')
SELECT * FROM public.memes WHERE tags @> ARRAY['cats'];

-- ----------------------------------------------------------------------
-- 9. UPDATE (Memperbarui Data termasuk category & tags)
-- ----------------------------------------------------------------------
UPDATE public.memes
SET
    title = 'Judul Meme yang Sudah Diperbaiki',
    description = 'Deskripsi telah diperbarui pada ' || NOW()::DATE,
    category = 'Wholesome',
    tags = ARRAY['cats','funny']
WHERE
    id = 1; -- Ganti 1 dengan ID meme yang ingin Anda perbarui

-- Jika Anda ingin menambah satu tag ke array tanpa menimpa
UPDATE public.memes
SET tags = array_append(tags, 'newtag')
WHERE id = 1;

-- ----------------------------------------------------------------------
-- 10. DELETE (Menghapus Data)
-- ----------------------------------------------------------------------

-- Menghapus meme berdasarkan ID
DELETE FROM public.memes
WHERE
    id = 1; -- Ganti 1 dengan ID meme yang ingin Anda hapus

-- Menghapus semua data dari tabel (gunakan dengan sangat hati-hati!)
-- TRUNCATE TABLE public.memes RESTART IDENTITY;

-- ----------------------------------------------------------------------
-- 11. NOTES
-- - This script uses `tags` as a `text[]`. If you prefer JSON storage, replace
--   `tags TEXT[]` with `tags JSONB` and adapt inserts/queries accordingly.
-- - If you enable stricter RLS, ensure INSERT/UPDATE policies include checks
--   that account for the new columns when using WITH CHECK clauses.
-- - After running this, your frontend may send `tags` as an array (e.g. from JS),
--   which maps cleanly to `text[]` when using Supabase JS client.
-- ----------------------------------------------------------------------
